name: quick_HeterBaseline_opv2v_camera_pyramid_dpt
root_dir: "dataset/OPV2V_small/train"
validate_dir: "dataset/OPV2V_small/test"
test_dir: "dataset/OPV2V_small/test"

yaml_parser: "load_general_params"
train_params:
  batch_size: &batch_size 1
  epoches: 1
  eval_freq: 1
  save_freq: 1
  max_cav: 5

comm_range: 70
input_source: ['camera', 'depth']
label_type: 'camera'
cav_lidar_range: &cav_lidar [-51.2, -51.2, -3, 51.2, 51.2, 1]

add_data_extension: []

heter:
  assignment_path: "opencood/logs/heter_modality_assign/opv2v_4modality.json" 
  ego_modality: &ego_modality "m2"
  mapping_dict:
    m1: m2
    m2: m2
    m3: m2
    m4: m2
  modality_setting:
    m2:
      sensor_type: &sensor_type_m2 'camera'
      core_method: &core_method_m2 "dpt_lift_splat_shoot"

      grid_conf: &grid_conf_m2
        xbound: [-51.2, 51.2, 0.4]
        ybound: [-51.2, 51.2, 0.4]
        zbound: [-10, 10, 20.0]
        ddiscr: [2, 50, 48]
        mode: 'LID'
      data_aug_conf: &data_aug_conf_m2
        resize_lim: [0.65, 0.7]
        final_dim: [384, 512]
        rot_lim: [-3.6, 3.6]
        H: 600
        W: 800
        rand_flip: False
        bot_pct_lim: [0.0, 0.05]
        cams: ['camera0', 'camera1', 'camera2', 'camera3']
        Ncams: 4


fusion:
  core_method: 'intermediateheter'
  dataset: 'opv2v'
  args: 
    proj_first: false
    grid_conf: None
    data_aug_conf: None


preprocess:
  core_method: BasePreprocessor
  args:
    sample_num: 1
    voxel_size: [0.4, 0.4, 4]
  cav_lidar_range: *cav_lidar

postprocess:
  core_method: 'VoxelPostprocessor'
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2
    num: &anchor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: 'hwl'
  max_num: 150
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

model:
  core_method: heter_pyramid_collab
  args:
    lidar_range: *cav_lidar
    supervise_single: true

    m2:
      core_method: *core_method_m2
      sensor_type: *sensor_type_m2

      encoder_args:
        anchor_number: *anchor_num
        grid_conf: *grid_conf_m2
        data_aug_conf: *data_aug_conf_m2
        img_downsample: 8
        img_features: &img_feature 128
        use_depth_gt: true
        depth_supervision: false
        camera_encoder: EfficientNet
        # DPT/DepthAnything3 settings
        dpt_root: "/home/qqxluca/vggt_series_4_coop/Depth-Anything-3/src"
        dpt_model_name: "da3-large"
        dpt_pretrained: "depth-anything/DA3-LARGE-1.1"
        dpt_freeze: true
        dpt_use_amp: true
        dpt_amp_dtype: "bf16"
        dpt_patch_size: 14
        dpt_resize: null
        depth_min: 0.1
        depth_max: 80.0

      camera_mask_args:
        cav_lidar_range: *cav_lidar
        grid_conf: *grid_conf_m2

      backbone_args:
        layer_nums: [3]
        layer_strides: [2]
        num_filters: [64]
        inplanes: 128

      aligner_args:
        core_method: identity

    fusion_backbone: 
      resnext: true
      layer_nums: [3, 5, 8]
      layer_strides: [1, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]
      anchor_number: *anchor_num

    shrink_header: 
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384

    in_head: 256
    anchor_number: *anchor_num
    dir_args: *dir_args


loss:
  core_method: point_pillar_pyramid_loss
  args:
    pos_cls_weight: 2.0
    cls:
      type: 'SigmoidFocalLoss'
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: 'WeightedSmoothL1Loss'
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: 'WeightedSoftmaxClassificationLoss'
      weight: 0.2
      args: *dir_args
    depth:
      weight: 0.0
    pyramid:
      relative_downsample: [1, 2, 4]
      weight: [0.4, 0.2, 0.1]


optimizer:
  core_method: Adam
  lr: 0.002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size: [15, 30]
